# Generated by Django 5.2.4 on 2025-07-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleregistry',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
