# Generated by Django 5.2.4 on 2025-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
